---
- hosts: localhost
  connection: local
  become: true
  vars:
    - gosu_ver: '1.9'
  tasks:
    - name: Installing apt-transport-https
      apt:
        name: "apt-transport-https"
        state: "present"

    - name: Installing ca-certificates
      apt:
        name: "ca-certificates"
        state: "latest"

    - name: Installing gosu
      get_url:
        url: "https://github.com/tianon/gosu/releases/download/{{ gosu_ver }}/gosu-amd64"
        dest: "/usr/local/bin/gosu"
        mode: 0755

    - name: Installing MongoDB
      apt:
        name: "mongodb"
        state: "present"

    - name: Creating Folders
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "mongodb"
        group: "mongodb"
      with_items:
        - '/data/db'
        - '/data/configdb'
